### ISSUE TITLE
Ansible playbook version

### ISSUE THREAD

**Issue by laperss** [laperss/xerces_cloud#15]
Two problems with current script 

1) README says "Ansible only needs to be installed on your local pc. Connection to the different VMs goes through SSH." - I'm pretty sure this is not the case since we only have a limited amount of floating IP:s. Wasn't this the reason for us using a "devVM" in the first place?

2) I cannot run script from devVM, looking into the reason for this. Error message:
```bash
ERROR! The field 'changed_when' is supposed to be a string type, however the incoming data structure is a <class 'ansible.parsing.yaml.objects.AnsibleSequence'>

The error appears to have been in '/home/ubuntu/playbook.yml': line 7, column 5, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  pre_tasks:
  - name: Install Python 2
    ^ here
```
Looks like it might be a YAML syntax error.

**Comment by laperss** [comment]
The error looks similar to what is reported [here](https://github.com/ansible/ansible/issues/13905) - i.e. that a string and not a list should follow the "changed_when" command.

@quilder have you been able to run the script you wrote? Which version of Ansible did you install?

**Comment by laperss** [comment]
This works for me: 
```
    changed_when: "{{item}}"
    with_items:
    - "output.stdout != ''"
    - "output.stdout != '\r\n'"
```

**Comment by quilder** [comment]
In that case you have to run it on a devVM that is correct. I didn't get this error though. Glad it is solved.

**Comment by ghost** [comment]
Yes you are correct regarding running it on the devVM. The fact that you should not run it on the VM that you want to deploy it to still stands. 

I tried your changes, but it gives me the following error
```
 [WARNING]: when statements should not include jinja2 templating delimiters
such as {{ }} or {% %}. Found: {{item}}

changed: [129.192.68.50] => (item=output.stdout != '')
fatal: [129.192.68.50]: FAILED! => {"failed": true, "msg": "The conditional check '{{item}}' failed. The error was: Invalid conditional detected: EOL while scanning string literal (<unknown>, line 1)"}
```
I am using ansible 2.3.0.0, and you?

**Comment by laperss** [comment]
I'm running Ansible 2.0.0.2 on the VM, that might be the problem then.
